name: Deploy CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn build
      env:
        CI: true
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}